export const DB_NAME = 'AlmoxarifadoDB';
export const DB_VERSION = 1;

export const STORES = {
    ITEMS: 'items',
    COLLABORATORS: 'collaborators',
    DEBITS: 'debits',
    LOGS: 'logs',
    SETTINGS: 'settings',
    SERVICE_ORDERS: 'service_orders',
    KITS: 'kits'
};

export const MODAL_IDS = {
    SETTINGS: 'settings-modal',
    ITEM_FORM: 'item-form-modal',
    ITEM_BATCHES: 'item-batches-modal',
    ITEM_HISTORY: 'item-history-modal',
    ITEM_MAINTENANCE: 'item-maintenance-modal',
    MOVEMENT: 'movement-modal',
    MASS_ADD: 'mass-add-modal',
    ALLOCATION: 'allocation-modal',
    COLLABORATOR: 'collaborator-modal',
    LOSS_REGISTRATION: 'loss-registration-modal',
    MASS_ADD_COLLABORATOR: 'mass-add-collaborator-modal',
    CONFIRMATION: 'confirmation-modal',
    QUICK_ENTRY: 'quick-entry-modal',
    DIRECT_LOSS: 'direct-loss-modal',
    ADJUSTMENT: 'adjustment-modal',
    BARCODE_ACTION: 'barcode-action-modal',
    LABEL_PRINT: 'label-print-modal',
    ITEM_KIT: 'item-kit-modal',
    KIT_RETURN: 'kit-return-modal',
    SERVICE_ORDER: 'service-order-modal',
    SERVICE_ORDER_DETAILS: 'service-order-details-modal'
};

export const ACTIONS = {
    MANAGE_ALLOCATIONS: 'manage-allocations',
    RETURN_ALLOCATION: 'return-allocation',
    REGISTER_LOSS: 'register-loss',
    ADJUST_STOCK: 'adjust-stock',
    MANAGE_MAINTENANCE: 'manage-maintenance',
    REPLACE_ITEM: 'replace-item',
    QUICK_ADD_STOCK: 'quick-add-stock',
    DO_COUNT: 'do-count',
    DELETE_TYPE: 'delete-type',
    ADD_NEW_TYPE: 'add-new-type',
    TOGGLE_DASHBOARD: 'toggle-dashboard',
    CLEAR_ALL_NOTIFICATIONS: 'clear-all-notifications',
    DISMISS_MANUAL_ALERT: 'dismiss-manual-alert',
    DO_BACKUP: 'do-backup',
    SEND_SUMMARY_EMAIL: 'send-summary-email',
    CANCEL_SETTINGS: 'cancel-settings',
    CANCEL_ITEM_FORM: 'cancel-item-form-modal',
    CANCEL_ITEM_BATCHES: 'cancel-item-batches-modal',
    CANCEL_ITEM_HISTORY: 'cancel-item-history-modal',
    CANCEL_ITEM_MAINTENANCE: 'cancel-item-maintenance-modal',
    CANCEL_ADJUSTMENT: 'cancel-adjustment',
    CANCEL_MOVEMENT: 'cancel-movement',
    CANCEL_MASS_ADD: 'cancel-mass-add',
    CANCEL_MASS_ADD_COLLABORATOR: 'cancel-mass-add-collaborator',
    CANCEL_LOSS: 'cancel-loss',
    CANCEL_DIRECT_LOSS: 'cancel-direct-loss',
    CANCEL_COLLABORATOR: 'cancel-collaborator',
    CANCEL_QUICK_ENTRY: 'cancel-quick-entry',
    CANCEL_CONFIRMATION: 'cancel-confirmation',
    CLOSE_ALLOCATION: 'close-allocation',
    CANCEL_BARCODE_ACTION: 'cancel-barcode-action',
    CANCEL_KIT_MANAGEMENT: 'cancel-kit-management',
    CANCEL_KIT_RETURN: 'cancel-kit-return',
    CANCEL_SERVICE_ORDER: 'cancel-service-order',
    CANCEL_SERVICE_ORDER_DETAILS: 'cancel-service-order-details',
    REMOVE_ITEM_FROM_OS: 'remove-item-from-os',
    MASS_ADD_FROM_KIT: 'mass-add-from-kit'
};
